import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const bidders=[
 {name:'ABC Technologies Pvt. Ltd.',score:94,risk:'Low',issue:'Fully verified',state:'Verified'},
 {name:'Bharat Digital Systems',score:86,risk:'Medium',issue:'OEM authorization review',state:'Needs Review'},
 {name:'Nova Infotech Pvt. Ltd.',score:72,risk:'Medium',issue:'Turnover discrepancy',state:'Needs Review'},
 {name:'Vertex Solutions',score:61,risk:'High',issue:'Missing statutory documents',state:'Review'},
 {name:'SecureTech India',score:48,risk:'High',issue:'Multiple compliance issues',state:'Review'}
];
const nav=['Dashboard','Tenders','Bid Verification','Compliance Analysis','Risk Center','Reports','Audit Trail','Integrations','Settings'];
const icons=['▦','◇','✓','▤','◉','▱','◷','⌁','⚙'];
const requirements=[
 ['GST Registration','verified','GSTIN 09ABCDE1234F1Z5','Active registration · Last verified 2 min ago'],
 ['Udyam Registration','verified','UDYAM-UP-09-0023412','Micro enterprise · ABC Technologies Pvt. Ltd.'],
 ['PAN / Income Tax','verified','PAN ABCDE1234F','Name and PAN matched across submitted documents'],
 ['Turnover Requirement','review','Minimum turnover: ₹5 Crore','Extracted: ₹4.72 Crore · Officer review required'],
 ['OEM Authorization','failed','Authorization validity not detected','Required authorization needs manual verification']
];
function Badge({children,type}){return <span className={'badge '+(type||'')}>{children}</span>}
function App(){
 const [authenticated,setAuthenticated]=useState(false),[page,setPage]=useState('Dashboard'),[collapsed,setCollapsed]=useState(false),[showWorkflow,setWorkflow]=useState(false),[step,setStep]=useState(1),[query,setQuery]=useState(''),[selected,setSelected]=useState('ABC Technologies Pvt. Ltd.'),[expanded,setExpanded]=useState(null),[decision,setDecision]=useState(null),[remark,setRemark]=useState(''),[toast,setToast]=useState('');
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const shown=bidders.filter(b=>b.name.toLowerCase().includes(query.toLowerCase()));
 const selectPage=p=>{setPage(p); if(p==='Bid Verification')setSelected('ABC Technologies Pvt. Ltd.')};
 if(!authenticated)return <Login onSignIn={()=>setAuthenticated(true)}/>;
 return <div className={'app '+(collapsed?'collapsed':'')}>
  <aside className="sidebar"><div className="brand"><div className="logo">G</div>{!collapsed&&<div><b>GeM Compliance AI</b><small>AI-POWERED PROCUREMENT</small></div>}</div>
   <button className="collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?'›':'‹'}</button>
   <nav>{nav.map((n,i)=><button key={n} className={page===n?'active':''} onClick={()=>selectPage(n)}><i>{icons[i]}</i>{!collapsed&&n}</button>)}</nav>
   <div className="officer"><div className="avatar">PO</div>{!collapsed&&<div><b>Procurement Officer</b><small><em/> Online</small></div>}</div></aside>
  <main><header><div className="crumb">Workspace <span>/</span> {page}</div><div className="header-actions"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tender, bidder, GSTIN..."/></div><button className="icon-btn" onClick={()=>notify('3 compliance issues require review')}>♧<sup>3</sup></button><button className="icon-btn">?</button><div className="profile"><div className="avatar">PO</div><span>Procurement Officer</span><b>⌄</b></div></div></header>
   <section className="content">
    {page==='Dashboard'&&<Dashboard onNew={()=>{setStep(1);setWorkflow(true)}} onPage={selectPage} shown={shown}/>} 
    {page==='Bid Verification'&&<Verification selected={selected} setSelected={setSelected} expanded={expanded} setExpanded={setExpanded} onDecision={setDecision} notify={notify}/>}
    {page==='Risk Center'&&<Risk shown={shown} onReview={b=>{setSelected(b.name);setPage('Bid Verification')}}/>}
    {page==='Integrations'&&<Integrations notify={notify}/>}
    {page==='Reports'&&<Reports notify={notify}/>}
    {page==='Audit Trail'&&<Audit/>}
    {!['Dashboard','Bid Verification','Risk Center','Integrations','Reports','Audit Trail'].includes(page)&&<Placeholder title={page} onNew={()=>setWorkflow(true)}/>} 
   </section>
  </main>
  {showWorkflow&&<Workflow step={step} setStep={setStep} close={()=>setWorkflow(false)} notify={notify}/>} 
  {decision&&<Decision type={decision} remark={remark} setRemark={setRemark} close={()=>setDecision(null)} notify={notify}/>} 
  {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}
function Login({onSignIn}){
 const [showPassword,setShowPassword]=useState(false);
 return <div className="login-page"><div className="login-panel"><div className="login-brand"><div className="logo">G</div><div><b>GeM Compliance AI</b><small>AI-POWERED PROCUREMENT VERIFICATION</small></div></div><p className="eyebrow">SECURE PROCUREMENT WORKSPACE</p><h1>Intelligent procurement compliance</h1><p className="login-sub">AI-powered verification and decision support for GeM procurement officers.</p><div className="security-points"><span>✓ Role-based access</span><span>✓ Encrypted evidence storage</span><span>✓ Complete audit traceability</span></div></div><form className="login-card" onSubmit={e=>{e.preventDefault();onSignIn()}}><div className="login-logo">G</div><h2>Welcome back</h2><p>Sign in to your authorized officer workspace.</p><label>Official email<input type="email" defaultValue="officer@cpse.gov.in" required/></label><label>Password<span className="password-field"><input type={showPassword?'text':'password'} defaultValue="Procurement@2026" required/><button type="button" className="password-toggle" aria-label={showPassword?'Hide password':'Show password'} title={showPassword?'Hide password':'Show password'} onClick={()=>setShowPassword(!showPassword)}>{showPassword?'◉':'◌'}</button></span></label><div className="remember"><label><input type="checkbox" defaultChecked/> Remember me</label><button type="button">Forgot password?</button></div><button className="primary sign-in">Sign in securely →</button><div className="authorized">⌾ Authorized Procurement Personnel Only</div></form></div>
}
function Dashboard({onNew,onPage,shown}){const kpis=[['◈','12','Active Tenders','+2 this month'],['◷','28','Bids Under Verification','6 due today'],['◉','8','Pending Reviews','Action needed'],['⚠','4','High Risk Bidders','2 new this week'],['✓','146','Verified Bids','+12.5%'],['◌','18 min','Avg. Verification Time','4 min faster']];return <>
 <div className="hero"><div><p className="eyebrow">PROCUREMENT COMMAND CENTER</p><h1>Good morning, Procurement Officer</h1><p>Here’s your procurement compliance overview.</p></div><div><button className="secondary">⇩ Generate Report</button><button className="primary" onClick={onNew}>＋ New Verification</button></div></div>
 <div className="ai-notice"><span>✦</span><div><b>AI assists — Officer decides</b><p>All AI assessments are advisory. Final qualification and disqualification decisions remain with the Procurement Officer.</p></div><button>Learn more →</button></div>
 <div className="kpis">{kpis.map(x=><div className="kpi" key={x[2]}><div className="kpi-icon">{x[0]}</div><small>{x[2]}</small><strong>{x[1]}</strong><span className={x[3].includes('Action')?'warn':'trend'}>{x[3]}</span></div>)}</div>
 <div className="analytics"><div className="card chart"><div className="card-title"><div><h3>Compliance overview</h3><p>Verification outcomes across active tenders</p></div><button>Last 7 days⌄</button></div><div className="chart-body"><div className="donut"><div><b>186</b><small>Total bids</small></div></div><div className="legend"><p><i className="dot green"/> Compliant <b>146</b><span>78%</span></p><p><i className="dot amber"/> Needs review <b>28</b><span>15%</span></p><p><i className="dot red"/> Non-compliant <b>12</b><span>7%</span></p></div></div></div><div className="card activity"><div className="card-title"><div><h3>Verification activity</h3><p>Document processing & review trends</p></div><button>Weekly⌄</button></div><div className="line-chart"><div className="gridlines"/><svg viewBox="0 0 500 160" preserveAspectRatio="none"><polyline points="0,120 70,105 140,119 210,70 280,90 350,45 430,58 500,20" fill="none" stroke="#1976d2" strokeWidth="4"/><polyline points="0,145 70,135 140,140 210,115 280,130 350,95 430,110 500,78" fill="none" stroke="#14a28b" strokeWidth="3"/></svg><div className="axis"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div><div className="chart-key"><span><i className="dot blue"/>Documents verified</span><span><i className="dot teal"/>Issues detected</span></div></div></div>
 <div className="card table-card"><div className="card-title"><div><h3>Recent tender verification</h3><p>Track the latest verification activity</p></div><button onClick={()=>onPage('Tenders')}>View all →</button></div><table><thead><tr><th>TENDER ID</th><th>TENDER TITLE</th><th>TOTAL BIDS</th><th>VERIFIED</th><th>PENDING</th><th>HIGH RISK</th><th>STATUS</th><th/></tr></thead><tbody><tr><td className="link">GEM/2026/B/10234</td><td><b>Supply of IT Equipment</b><small>Central Public Sector Enterprise</small></td><td>8</td><td className="positive">6</td><td className="warning">2</td><td className="danger">1</td><td><Badge type="progress">In Progress</Badge></td><td><button className="view" onClick={()=>onPage('Bid Verification')}>View →</button></td></tr><tr><td className="link">GEM/2026/B/09821</td><td><b>Network Infrastructure</b><small>National Informatics Centre</small></td><td>12</td><td className="positive">12</td><td>0</td><td>0</td><td><Badge type="verified">Completed</Badge></td><td><button className="view">View →</button></td></tr></tbody></table></div>
 </>}
function Verification({selected,setSelected,expanded,setExpanded,onDecision,notify}){const bidder=bidders.find(x=>x.name===selected)||bidders[0];return <><div className="verify-head"><div><button className="back">← Back to verifications</button><h1>{bidder.name}</h1><p>Supply of IT Equipment <span>•</span> GEM/2026/B/10234</p></div><div><button className="secondary" onClick={()=>notify('Compliance report prepared')}>⇩ Export report</button><button className="primary" onClick={()=>onDecision('Approve / Qualify')}>Final review →</button></div></div><div className="assessment"><div className="score"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="42"/><circle className="score-ring" cx="50" cy="50" r="42" style={{strokeDashoffset:264-(264*bidder.score/100)}}/></svg><div><b>{bidder.score}</b><span>/100</span><small>Compliance score</small></div></div><div className="assessment-copy"><p className="eyebrow">AI VERIFICATION COMPLETE</p><h2>{bidder.score>=85?'Strong compliance profile':'Review attention required'}</h2><p>Evidence has been analyzed against 12 tender-specific requirements.</p><div><Badge type={bidder.risk==='Low'?'verified':'review'}>{bidder.risk.toUpperCase()} RISK</Badge><Badge type="progress">{bidder.state}</Badge></div></div><div className="review-summary"><b>8 <small>Verified</small></b><b>2 <small>Needs review</small></b><b>2 <small>Not verified</small></b></div></div><div className="advisory">✦ <b>AI-generated assessment.</b> Final qualification/disqualification decision must be made by the Procurement Officer.</div>
<div className="split"><div><div className="section-title"><div><h2>Compliance requirements</h2><p>Evidence-based AI assessment for this bidder</p></div><button className="secondary">Filter: All⌄</button></div>{requirements.map((r,i)=><div className={'requirement '+(expanded===i?'open':'')} key={r[0]}><button className="req-top" onClick={()=>setExpanded(expanded===i?null:i)}><span className={'status-icon '+r[1]}>{r[1]==='verified'?'✓':r[1]==='review'?'!':'×'}</span><div><b>{r[0]}</b><small>{r[1]==='verified'?'VERIFIED':r[1]==='review'?'NEEDS REVIEW':'NOT VERIFIED'}</small></div><span className="chev">⌄</span></button>{expanded===i&&<div className="req-details"><div><small>{r[2]}</small><b>{r[3]}</b></div><p>{r[1]==='review'?'Submitted financial documents indicate turnover below the tender threshold. Officer review is required.':r[1]==='failed'?'Required document was not found or could not be verified. Request clarification or verify manually.':'Source verified through document extraction and cross-document matching.'}</p><div><button className="secondary" onClick={()=>notify('Evidence viewer opened for '+r[0])}>View evidence</button><button className="text-btn" onClick={()=>notify('Auditable reasoning summary opened')}>✦ Why?</button></div></div>}</div>)}</div><aside className="right-panel"><h3>Verification details</h3><div className="detail"><small>Verification ID</small><b>VRF-2026-08492</b></div><div className="detail"><small>Processed on</small><b>23 Aug 2026, 10:42 AM</b></div><div className="detail"><small>Documents analyzed</small><b>7 documents</b></div><hr/><h3>Consistency check</h3><p className="inconsistency">⚠ Potential mismatch requiring officer review.</p><div className="match"><span>Company name</span><Badge type="review">Variation</Badge></div><div className="match"><span>PAN</span><Badge type="verified">Match</Badge></div><div className="match"><span>GSTIN</span><Badge type="verified">Match</Badge></div><button className="full secondary" onClick={()=>notify('Consistency report opened')}>View consistency report</button></aside></div></>}
function Workflow({step,setStep,close,notify}){const steps=['Tender details','Tender document','Bidder documents','AI verification']; const complete=step===4;return <div className="modal-bg"><div className="workflow"><button className="close" onClick={close}>×</button><p className="eyebrow">NEW VERIFICATION</p><h2>{complete?'AI verification in progress':'Create a tender verification'}</h2><div className="steps">{steps.map((s,i)=><span key={s} className={step===i+1?'current':step>i+1?'done':''}><i>{step>i+1?'✓':i+1}</i>{s}</span>)}</div>{step===1&&<div className="form"><label>Tender ID<input defaultValue="GEM/2026/B/10234"/></label><label>Tender title<input defaultValue="Supply of IT Equipment"/></label><label>Department / organization<select><option>Central Public Sector Enterprise</option></select></label><label>Tender category<select><option>IT & Electronics</option></select></label></div>}{step===2&&<Upload title="Upload Tender Document" text="Drop a PDF or DOCX to extract tender requirements." file="IT_Equipment_Tender.pdf"/>}{step===3&&<Upload title="Upload Bid Documents" text="Upload documents received from GeM for verification." file="GST_Certificate.pdf  ·  Udyam_Certificate.pdf  ·  PAN.pdf"/>}{step===4&&<div className="processing"><div className="loader">✦</div><h3>Analyzing tender & bidder documents</h3><p>88% complete · This takes a moment</p>{['Document extraction','Tender requirement extraction','GST verification','Udyam verification','PAN verification','Cross-document consistency check','Risk assessment','Compliance report'].map((x,i)=><div className={'process '+(i<5?'done':i===5?'active':'')} key={x}><span>{i<5?'✓':i===5?'◉':'○'}</span>{x}<small>{i<5?'Complete':i===5?'In progress':''}</small></div>)}</div>}<div className="modal-footer"><button className="secondary" onClick={step===1?close:()=>setStep(step-1)}>Back</button><button className="primary" onClick={()=>complete?(close(),notify('Verification completed — report is ready')):setStep(step+1)}>{complete?'View compliance report':'Continue →'}</button></div></div></div>}
function Upload({title,text,file}){return <div className="upload"><div className="upload-icon">⇧</div><h3>{title}</h3><p>{text}</p><button className="secondary">Choose files</button><div className="uploaded">✓ <b>{file}</b><span>AI extraction ready</span></div></div>}
function Decision({type,remark,setRemark,close,notify}){return <div className="modal-bg"><div className="decision"><button className="close" onClick={close}>×</button><p className="eyebrow">FINAL PROCUREMENT REVIEW</p><h2>{type} bidder?</h2><div className="advisory">⚠ <b>AI recommendations are advisory only.</b> The Procurement Officer is solely responsible for the final procurement decision.</div><p>I have reviewed the available evidence and am making this decision based on my assessment.</p><label>Officer remarks <textarea value={remark} onChange={e=>setRemark(e.target.value)} placeholder="Add mandatory decision remarks..."/></label><div className="modal-footer"><button className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={!remark} onClick={()=>{close();notify(type+' recorded in audit trail')}}>Confirm decision</button></div></div></div>}
function Risk({shown,onReview}){return <><div className="hero"><div><p className="eyebrow">RISK INTELLIGENCE</p><h1>Bidder risk center</h1><p>Prioritize evidence-based review across active tenders.</p></div></div><div className="risk-stats"><div><b>4</b><span>High risk bidders</span></div><div><b>11</b><span>Medium risk bidders</span></div><div><b>13</b><span>Low risk bidders</span></div></div><div className="card table-card"><div className="card-title"><div><h3>Risk queue</h3><p>Sorted by potential impact</p></div><button className="secondary">Filter risk⌄</button></div><table><thead><tr><th>BIDDER</th><th>TENDER</th><th>SCORE</th><th>RISK</th><th>MAIN ISSUE</th><th>ACTION</th></tr></thead><tbody>{shown.map(b=><tr key={b.name}><td><b>{b.name}</b></td><td className="link">GEM/2026/B/10234</td><td><b>{b.score}/100</b></td><td><Badge type={b.risk.toLowerCase()}>{b.risk}</Badge></td><td>{b.issue}</td><td><button className="view" onClick={()=>onReview(b)}>Review →</button></td></tr>)}</tbody></table></div></>}
function Integrations({notify}){let list=['GSTN','Udyam / MSME','PAN / Income Tax','MCA21','Startup India','DigiLocker','BIS / DPIIT','Blacklisting / Debarment'];return <><div className="hero"><div><p className="eyebrow">GOVERNMENT SOURCE VERIFICATION</p><h1>Integrations</h1><p>Connection status and verification activity for official data sources.</p></div></div><div className="integration-grid">{list.map((x,i)=><div className="card integration" key={x}><div className="int-icon">{x.slice(0,2)}</div><div><h3>{x}</h3><Badge type={i===3?'review':'verified'}>{i===3?'Sandbox':'Demo connected'}</Badge></div><p>Last synchronized {i===3?'1 day':'2 minutes'} ago</p><b>{1248-i*103} <small>verification requests</small></b><button onClick={()=>notify(x+' integration settings opened')}>Configure →</button></div>)}</div><p className="demo-note">All integrations are clearly labelled Demo / Sandbox in this prototype; no live government system access is implied.</p></>}
function Reports({notify}){return <><div className="hero"><div><p className="eyebrow">AUDITABLE OUTPUTS</p><h1>Reports</h1><p>Generate procurement-ready compliance and risk reports.</p></div></div><div className="report-grid">{['Bid Compliance Report','Tender Compliance Summary','Risk Assessment Report','Audit Report','Government Verification Report'].map(x=><div className="card report" key={x}><div>▧</div><h3>{x}</h3><p>Exported with tender-specific evidence and officer review trail.</p><button className="primary" onClick={()=>notify(x+' generated')}>Generate report</button></div>)}</div></>}
function Audit(){return <><div className="hero"><div><p className="eyebrow">EVIDENCE TRACEABILITY</p><h1>Audit trail</h1><p>Every verification and officer action in one immutable review log.</p></div><button className="secondary">⇩ Export logs</button></div><div className="card table-card"><table><thead><tr><th>TIMESTAMP</th><th>USER</th><th>TENDER</th><th>BIDDER</th><th>ACTION</th><th>RESULT</th></tr></thead><tbody>{[['10:21 AM','Procurement Officer','GEM/2026/B/10234','ABC Technologies','GST Verification','Completed'],['10:24 AM','AI Verification Engine','GEM/2026/B/10234','ABC Technologies','OEM Authorization','Issue detected'],['10:31 AM','Procurement Officer','GEM/2026/B/10234','ABC Technologies','Compliance reviewed','Recorded']].map(r=><tr key={r[0]}>{r.map((x,i)=><td key={i}>{i===5?<Badge type={x==='Completed'?'verified':'review'}>{x}</Badge>:x}</td>)}</tr>)}</tbody></table></div></>}
function Placeholder({title,onNew}){return <div className="empty"><div>◈</div><h1>{title}</h1><p>This working prototype is ready to be configured for your procurement process.</p><button className="primary" onClick={onNew}>＋ Start new verification</button></div>}
createRoot(document.getElementById('root')).render(<App/>);
